apiVersion: v2
name: compliance-platform
description: OpenShift platform compliance remediations (no reboot).
type: application
version: 0.0.0
appVersion: "0.1.82"
keywords:
  - compliance
  - openshift
  - hardening
  - openscap
