{{- define "cr.frag.kubeletconfig-compliance-kubelet-enable-streaming-connections.ocp4-kubelet-enable-streaming-connections.0" -}}
spec:
  kubeletConfig:
    streamingConnectionIdleTimeout: {{ .Values.variables.var_streaming_connection_timeouts }}
{{- end -}}

{{- /* KubeletConfig/compliance-kubelet-enable-streaming-connections - rule(s): ocp4-kubelet_enable_streaming_connections */ -}}
{{- if and (.Values.node.enabled) (eq (include "cr.anyActive" (dict "root" . "rules" (list "ocp4-kubelet_enable_streaming_connections"))) "true") -}}
{{- $merged := dict -}}
{{- if eq (include "cr.ruleActive" (dict "root" . "rule" "ocp4-kubelet_enable_streaming_connections")) "true" -}}
{{- $frag := include "cr.frag.kubeletconfig-compliance-kubelet-enable-streaming-connections.ocp4-kubelet-enable-streaming-connections.0" . | fromYaml -}}
{{- $merged = mustMergeOverwrite $merged $frag -}}
{{- end -}}
{{- range $role := (.Values.node.roles | uniq) }}
---
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: {{ printf "%s-%s" "compliance-kubelet-enable-streaming-connections" $role }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    compliance.openshift.io/managed: "true"
    machineconfiguration.openshift.io/role: {{ $role | quote }}
{{ $merged | toYaml }}
{{- end }}
{{- end -}}
