{{- define "cr.frag.machineconfig-75-ocp4-kubelet-enable-protect-kernel-sysctl.ocp4-kubelet-enable-protect-kernel-sysctl.0" -}}
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:,vm.overcommit_memory%3D1%0Avm.panic_on_oom%3D0%0Akernel.panic%3D10%0Akernel.panic_on_oops%3D1%0Akernel.keys.root_maxkeys%3D1000000%0Akernel.keys.root_maxbytes%3D25000000
        mode: 0644
        path: /etc/sysctl.d/90-kubelet.conf
        overwrite: true
{{- end -}}

{{- /* MachineConfig/75-ocp4-kubelet-enable-protect-kernel-sysctl - rule(s): ocp4-kubelet_enable_protect_kernel_sysctl */ -}}
{{- if and (.Values.node.enabled) (eq (include "cr.anyActive" (dict "root" . "rules" (list "ocp4-kubelet_enable_protect_kernel_sysctl"))) "true") -}}
{{- $merged := dict -}}
{{- if eq (include "cr.ruleActive" (dict "root" . "rule" "ocp4-kubelet_enable_protect_kernel_sysctl")) "true" -}}
{{- $frag := include "cr.frag.machineconfig-75-ocp4-kubelet-enable-protect-kernel-sysctl.ocp4-kubelet-enable-protect-kernel-sysctl.0" . | fromYaml -}}
{{- $merged = mustMergeOverwrite $merged $frag -}}
{{- end -}}
{{- range $role := (.Values.node.roles | uniq) }}
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: {{ printf "%s-%s" "75-ocp4-kubelet-enable-protect-kernel-sysctl" $role }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    compliance.openshift.io/managed: "true"
    machineconfiguration.openshift.io/role: {{ $role | quote }}
{{ $merged | toYaml }}
{{- end }}
{{- end -}}
