{{- define "cr.frag.machineconfig-75-ocp4-sysctl-net-ipv4-conf-all-rp-filter.rhcos4-sysctl-net-ipv4-conf-all-rp-filter.0" -}}
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:,net.ipv4.conf.all.rp_filter%3D1%0A
        mode: 0644
        path: /etc/sysctl.d/75-sysctl_net_ipv4_conf_all_rp_filter.conf
        overwrite: true
{{- end -}}

{{- /* MachineConfig/75-ocp4-sysctl-net-ipv4-conf-all-rp-filter - rule(s): rhcos4-sysctl_net_ipv4_conf_all_rp_filter */ -}}
{{- if and (.Values.node.enabled) (eq (include "cr.anyActive" (dict "root" . "rules" (list "rhcos4-sysctl_net_ipv4_conf_all_rp_filter"))) "true") -}}
{{- $merged := dict -}}
{{- if eq (include "cr.ruleActive" (dict "root" . "rule" "rhcos4-sysctl_net_ipv4_conf_all_rp_filter")) "true" -}}
{{- $frag := include "cr.frag.machineconfig-75-ocp4-sysctl-net-ipv4-conf-all-rp-filter.rhcos4-sysctl-net-ipv4-conf-all-rp-filter.0" . | fromYaml -}}
{{- $merged = mustMergeOverwrite $merged $frag -}}
{{- end -}}
{{- range $role := (.Values.node.roles | uniq) }}
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: {{ printf "%s-%s" "75-ocp4-sysctl-net-ipv4-conf-all-rp-filter" $role }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    compliance.openshift.io/managed: "true"
    machineconfiguration.openshift.io/role: {{ $role | quote }}
{{ $merged | toYaml }}
{{- end }}
{{- end -}}
