{{- define "cr.frag.machineconfig-75-ocp4-audit-rules-usergroup-modification-shadow.rhcos4-audit-rules-usergroup-modification-shadow.0" -}}
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:

          source: data:,-w%20/etc/shadow%20-p%20wa%20-k%20audit_rules_usergroup_modification%0A

        mode: 0644
        path: /etc/audit/rules.d/75-audit_rules_usergroup_modification_shadow.rules
        overwrite: true
{{- end -}}

{{- /* MachineConfig/75-ocp4-audit-rules-usergroup-modification-shadow - rule(s): rhcos4-audit_rules_usergroup_modification_shadow */ -}}
{{- if and (.Values.node.enabled) (eq (include "cr.anyActive" (dict "root" . "rules" (list "rhcos4-audit_rules_usergroup_modification_shadow"))) "true") -}}
{{- $merged := dict -}}
{{- if eq (include "cr.ruleActive" (dict "root" . "rule" "rhcos4-audit_rules_usergroup_modification_shadow")) "true" -}}
{{- $frag := include "cr.frag.machineconfig-75-ocp4-audit-rules-usergroup-modification-shadow.rhcos4-audit-rules-usergroup-modification-shadow.0" . | fromYaml -}}
{{- $merged = mustMergeOverwrite $merged $frag -}}
{{- end -}}
{{- range $role := (.Values.node.roles | uniq) }}
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: {{ printf "%s-%s" "75-ocp4-audit-rules-usergroup-modification-shadow" $role }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    compliance.openshift.io/managed: "true"
    machineconfiguration.openshift.io/role: {{ $role | quote }}
{{ $merged | toYaml }}
{{- end }}
{{- end -}}
