{{- define "cr.frag.machineconfig-75-ocp4-audit-rules-privileged-commands-fusermount.rhcos4-audit-rules-privileged-commands-fusermount.0" -}}
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:

          source: data:,-a%20always%2Cexit%20-F%20path%3D/usr/bin/fusermount%20-F%20auid%3E%3D1000%20-F%20auid%21%3Dunset%20-F%20key%3Dprivileged%0A

        mode: 0644
        path: /etc/audit/rules.d/75-usr_bin_fusermount_execution.rules
        overwrite: true
{{- end -}}

{{- /* MachineConfig/75-ocp4-audit-rules-privileged-commands-fusermount - rule(s): rhcos4-audit_rules_privileged_commands_fusermount */ -}}
{{- if and (.Values.node.enabled) (eq (include "cr.anyActive" (dict "root" . "rules" (list "rhcos4-audit_rules_privileged_commands_fusermount"))) "true") -}}
{{- $merged := dict -}}
{{- if eq (include "cr.ruleActive" (dict "root" . "rule" "rhcos4-audit_rules_privileged_commands_fusermount")) "true" -}}
{{- $frag := include "cr.frag.machineconfig-75-ocp4-audit-rules-privileged-commands-fusermount.rhcos4-audit-rules-privileged-commands-fusermount.0" . | fromYaml -}}
{{- $merged = mustMergeOverwrite $merged $frag -}}
{{- end -}}
{{- range $role := (.Values.node.roles | uniq) }}
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: {{ printf "%s-%s" "75-ocp4-audit-rules-privileged-commands-fusermount" $role }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    compliance.openshift.io/managed: "true"
    machineconfiguration.openshift.io/role: {{ $role | quote }}
{{ $merged | toYaml }}
{{- end }}
{{- end -}}
