{{- define "cr.frag.machineconfig-75-ocp4-service-autofs-disabled.rhcos4-service-autofs-disabled.0" -}}
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
      - name: autofs.service
        enabled: false
        mask: true
      - name: autofs.socket
        enabled: false
        mask: true
{{- end -}}

{{- /* MachineConfig/75-ocp4-service-autofs-disabled - rule(s): rhcos4-service_autofs_disabled */ -}}
{{- if and (.Values.node.enabled) (eq (include "cr.anyActive" (dict "root" . "rules" (list "rhcos4-service_autofs_disabled"))) "true") -}}
{{- $merged := dict -}}
{{- if eq (include "cr.ruleActive" (dict "root" . "rule" "rhcos4-service_autofs_disabled")) "true" -}}
{{- $frag := include "cr.frag.machineconfig-75-ocp4-service-autofs-disabled.rhcos4-service-autofs-disabled.0" . | fromYaml -}}
{{- $merged = mustMergeOverwrite $merged $frag -}}
{{- end -}}
{{- range $role := (.Values.node.roles | uniq) }}
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: {{ printf "%s-%s" "75-ocp4-service-autofs-disabled" $role }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    compliance.openshift.io/managed: "true"
    machineconfiguration.openshift.io/role: {{ $role | quote }}
{{ $merged | toYaml }}
{{- end }}
{{- end -}}
