{{- define "cr.frag.machineconfig-75-ocp4-sysctl-net-ipv4-conf-default-accept-source-route.rhcos4-sysctl-net-ipv4-conf-default-accept-source-route.0" -}}
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:,net.ipv4.conf.default.accept_source_route%3D0%0A
        mode: 0644
        path: /etc/sysctl.d/75-sysctl_net_ipv4_conf_default_accept_source_route.conf
        overwrite: true
{{- end -}}

{{- /* MachineConfig/75-ocp4-sysctl-net-ipv4-conf-default-accept-source-route - rule(s): rhcos4-sysctl_net_ipv4_conf_default_accept_source_route */ -}}
{{- if and (.Values.node.enabled) (eq (include "cr.anyActive" (dict "root" . "rules" (list "rhcos4-sysctl_net_ipv4_conf_default_accept_source_route"))) "true") -}}
{{- $merged := dict -}}
{{- if eq (include "cr.ruleActive" (dict "root" . "rule" "rhcos4-sysctl_net_ipv4_conf_default_accept_source_route")) "true" -}}
{{- $frag := include "cr.frag.machineconfig-75-ocp4-sysctl-net-ipv4-conf-default-accept-source-route.rhcos4-sysctl-net-ipv4-conf-default-accept-source-route.0" . | fromYaml -}}
{{- $merged = mustMergeOverwrite $merged $frag -}}
{{- end -}}
{{- range $role := (.Values.node.roles | uniq) }}
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: {{ printf "%s-%s" "75-ocp4-sysctl-net-ipv4-conf-default-accept-source-route" $role }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    compliance.openshift.io/managed: "true"
    machineconfiguration.openshift.io/role: {{ $role | quote }}
{{ $merged | toYaml }}
{{- end }}
{{- end -}}
