{{- define "cr.frag.machineconfig-75-ocp4-no-direct-root-logins.rhcos4-no-direct-root-logins.0" -}}
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:,
        mode: 0600
        path: /etc/securetty
        overwrite: true
{{- end -}}

{{- /* MachineConfig/75-ocp4-no-direct-root-logins - rule(s): rhcos4-no_direct_root_logins */ -}}
{{- if and (.Values.node.enabled) (eq (include "cr.anyActive" (dict "root" . "rules" (list "rhcos4-no_direct_root_logins"))) "true") -}}
{{- $merged := dict -}}
{{- if eq (include "cr.ruleActive" (dict "root" . "rule" "rhcos4-no_direct_root_logins")) "true" -}}
{{- $frag := include "cr.frag.machineconfig-75-ocp4-no-direct-root-logins.rhcos4-no-direct-root-logins.0" . | fromYaml -}}
{{- $merged = mustMergeOverwrite $merged $frag -}}
{{- end -}}
{{- range $role := (.Values.node.roles | uniq) }}
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: {{ printf "%s-%s" "75-ocp4-no-direct-root-logins" $role }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    compliance.openshift.io/managed: "true"
    machineconfiguration.openshift.io/role: {{ $role | quote }}
{{ $merged | toYaml }}
{{- end }}
{{- end -}}
