{{- define "cr.frag.machineconfig-75-ocp4-kubevirt-vcpu-metrics-enabled.ocp4-kubevirt-vcpu-metrics-enabled.0" -}}
spec:
  config:
    ignition:
      version: 3.1.0
  kernelArguments:
    - schedstats=enable
{{- end -}}

{{- /* MachineConfig/75-ocp4-kubevirt-vcpu-metrics-enabled - rule(s): ocp4-kubevirt-vcpu-metrics-enabled */ -}}
{{- if and (.Values.node.enabled) (eq (include "cr.anyActive" (dict "root" . "rules" (list "ocp4-kubevirt-vcpu-metrics-enabled"))) "true") -}}
{{- $merged := dict -}}
{{- if eq (include "cr.ruleActive" (dict "root" . "rule" "ocp4-kubevirt-vcpu-metrics-enabled")) "true" -}}
{{- $frag := include "cr.frag.machineconfig-75-ocp4-kubevirt-vcpu-metrics-enabled.ocp4-kubevirt-vcpu-metrics-enabled.0" . | fromYaml -}}
{{- $merged = mustMergeOverwrite $merged $frag -}}
{{- end -}}
{{- range $role := (.Values.node.roles | uniq) }}
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: {{ printf "%s-%s" "75-ocp4-kubevirt-vcpu-metrics-enabled" $role }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    compliance.openshift.io/managed: "true"
    machineconfiguration.openshift.io/role: {{ $role | quote }}
{{ $merged | toYaml }}
{{- end }}
{{- end -}}
