apiVersion: v2
name: compliance-node
description: OpenShift node compliance remediations (MachineConfig/KubeletConfig; reboots).
type: application
version: 0.1.0
appVersion: "0.1.82"
keywords:
  - compliance
  - openshift
  - hardening
  - openscap
